steps:
- name: 'gcr.io/$PROJECT_ID/slackbot'
  args: [ '--build', '$BUILD_ID', '--mode', 'trigger', '--webhook', '$_SLACK_ENDPOINT' ]
- name: 'gcr.io/cloud-builders/gcloud'
  args: ['beta', 'functions', 'deploy', 'cm-test-repo', '--trigger-http', '--runtime=nodejs6', '--entry-point=helloGET', '--source=$_SOURCE_CODE']
  dir: 'functions/autodeploy'

