steps:
- name: 'gcr.io/cloud-builders/yarn'
  args: ['install']
  dir: 'functions/autodeploy'
- name: 'gcr.io/cloud-builders/gcloud'
  args: ['functions', 'deploy', 'cm-test-repo', '--trigger-http', '--source', 'https://source.cloud.google.com/ae-lab/github_camillemch_test-gcp-repo/+/master:index.js', '--runtime', 'nodejs6', '--entry-point', "helloGET"]
  dir: 'functions/autodeploy'
