steps:
- name: 'gcr.io/ae-lab/slackbot'
  args: [ '--build', 'build.BuildId', '--mode', 'trigger', '--webhook', 'https://hooks.slack.com/services/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' ]
- name: 'gcr.io/cloud-builders/gcloud'
  args: ['beta', 'functions', 'deploy', 'cm-test-repo', '--trigger-http', '--runtime=nodejs6', '--entry-point=helloGET', '--source=https://source.developers.google.com/projects/ae-lab/repos/github_camillemch_test-gcp-repo']
  dir: 'functions/autodeploy'

