steps:
- name: 'gcr.io/cloud-builders/yarn'
  args: ['install']
  dir: 'functions/autodeploy'
- name: 'gcr.io/cloud-builders/gcloud'
  args: ['functions', 'deploy', 'cm-test-repo', '--trigger-http', '--runtime=nodejs6', '--entry-point=helloGET', '--source=https://source.developers.google.com/projects/ae-lab/repos/github_camillemhl_test-gcp-repo']
  dir: 'functions/autodeploy'
  
  

#steps:
#- name: 'gcr.io/cloud-builders/gcloud'
#  args:
#  - 'beta'
#  - 'functions'
#  - 'deploy'
#  - 'cm-test-repo'
#  - '--entry-point=helloGET'
#  - '--trigger-http'
